### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by jviquerat** [ppocma/ppocma#1]
Hi,

Thank you for this great contribution. If you don't mind, I have a few questions regarding the method:

- Tell me if I am wrong, but from what I understand, you end up not using the PPO clipped loss anymore, but something that looks more like a vanilla PG loss. Is that correct ?
- I do not understand your justification of the rank-mu update. The rank-mu update in CMAES supposes to use the covariance matrix history to compute the updated one, which indeed elongates the exploration distribution. However, I don't understand here why it is important to update the covariance before the mean ?

Thanks again for the great work.

**Comment by ppocma** [comment]
Hi,

Thanks a lot for your interest, and appologies for replying so late. We've been pretty busy with our other projects. Hopefully this is still something of interest to you.

- Yes, we don't use the clipped loss. The PG loss is stable when not using negative advantages.
- Fig. 3 in the paper shows the difference of updating the mean before the covariance (3C) and first updating the covariance (3D), i.e., using the old mean when computing variance as sum_i((x_i-mean)^2).

Thanks again for the great questions :)

**Comment by jviquerat** [comment]
Thanks for answering :) 
Q1 : ok, the "PPO" in "PPO-CMA" is a bit misleading then, as, strictly speaking, "PPO" refers to the clipped surrogate update
Q2 : yes indeed, in between I found the answer in the Hansen tutorial

Additional questions : 

- Is there a reason why you limited the method to diagonal covariance matrices ?
- Up to which control dimension have you tested the method ?

Thanks again for answering

**Comment by ppocma** [comment]
Q1: Schulman 2017 uses PPO in a more general sense, referring to algorithms that confine the updated policy to the proximity of the old policy. They describe two ways to do this, of which the clipped loss was recommended (although it’s effectiveness has later been questioned by https://arxiv.org/abs/2005.12729) . We call our method PPO-CMA because using the PG loss with only positive advantages achieves the same: Since the new policy is fitted to a subset of actions sampled from the old policy, the new policy cannot diverge far from the old one.

- We initially tested full covariances but observed poor convergence.

- We’ve tested PPO-CMA up to the MuJoCo humanoid, i.e. 17-dimensional actions.

Hope this helps :)

**Comment by jviquerat** [comment]
Yep, thanks for your answers :)
